language: python
dist: bionic # 18.04
python:
- '3.7'
install:
- git submodule update --init --recursive
- sudo apt-get update
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy matplotlib
  h5py cython
- source activate test-environment
#- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then conda install wxpython; else pip
#  -vvv install --pre -f https://wxpython.org/Phoenix/snapshot-builds/linux/gtk2/ubuntu-14.04/
#  --only-binary wxPython wxPython; fi
- pip install -vvv --pre --trusted-host www.coolprop.dreamhosters.com --find-links
  http://www.coolprop.dreamhosters.com/binaries/Python/ -U --force-reinstall CoolProp
- python setup.py install
- conda list
script:
- cd examples
- python simple_example.py
- python scroll_compressor.py
- python piston_expander.py
- cd ..
deploy:
  provider: pypi
  user: belli
  distributions: sdist
  password:
    secure: lMd4RExdT51duTZy8sUNCN8Yj0nZh2WAw7z50X1vBAgnshCAMRmPjREKU5QQoxXHwPf6b0xlbARQieNtDaNIGBodkJviFSByhcHO9a69/WW8OL+C+pAwNZWcjfv+ZifQatq+tEvjxoQqD5Szq9AMnrS3jmtuL9XdH0N4UkYRMck=
  on:
    tags: true
  skip_cleanup: true
notifications:
  email:
    recipients:
    - ian.h.bell@gmail.com
    on_success: never
    on_failure: always
